# Main working directory
workdir: "workflows/initial_workflow"

# Store all FASTA files here
fastadir: "workflows/initial_workflow/fasta"

# Each FASTA file needs an according .subset file in this folder (test1.fasta -> test1.subset)
subdir: "workflows/initial_workflow/subset_rules"

# annotation_cols: ['Taxonomic_lineage_PHYLUM', 'Taxonomic_lineage_SUPERKINGDOM',
# 'KARI_Class', 'Loop_Length', 'Cross-reference_SUPFAM',
# Cross-reference_Pfam', 'Cross-reference_OMA', 'BRENDA_KM', 'EC_number']

annotation_cols: ['Taxonomic_lineage_PHYLUM', 'Taxonomic_lineage_SUPERKINGDOM']

ancestor_cols: ['MOTIF_SPVEY : True']

blocked_datasets: ['uniprot_ec_4_2_1_9', 
'uniprot_ec_1_1_1_86_OR_ec_1_1_1_382_OR_ec_1_1_1_383', 'OMA_VHIVWND_uniprot_ec_2_2_1_6_swissprot', 
'OMA_VHIVWND_uniprot_ec_2_2_1_6_swissprot_cutdown']

# blocked_datasets: ['uniprot_ec_1_1_1_86']


brenda_cols : ['KM', 'TN']