# 2021 July Note: 'comment(ENZYME REGULATION)', 'context', 'tools'  are not returning a value correctly


full_uniprot_cols = ['id',
'entry name',
'genes',
'genes(PREFERRED)',
'genes(ALTERNATIVE)',
'genes(OLN)',
'genes(ORF)',
'organism',
'organism-id',
'protein names',
'sequence',
'proteome',
'lineage(ALL)',
'virus hosts',
'fragment',
'encodedon',
'comment(ALTERNATIVE PRODUCTS)',
'comment(ERRONEOUS GENE MODEL PREDICTION)',
'comment(ERRONEOUS INITIATION)',
'comment(ERRONEOUS TERMINATION)',
'comment(ERRONEOUS TRANSLATION)',
'comment(FRAMESHIFT)',
'comment(MASS SPECTROMETRY)',
'comment(POLYMORPHISM)',
'comment(RNA EDITING)',
'comment(SEQUENCE CAUTION)',
'length',
'mass',
'feature(ALTERNATIVE SEQUENCE)',
'feature(NATURAL VARIANT)',
'feature(NON ADJACENT RESIDUES)',
'feature(NON STANDARD RESIDUE)',
'feature(NON TERMINAL RESIDUE)',
'feature(SEQUENCE CONFLICT)',
'feature(SEQUENCE UNCERTAINTY)',
'version(sequence)',
'ec',
'comment(ABSORPTION)',
'comment(CATALYTIC ACTIVITY)',
'chebi',
'chebi(Catalytic activity)',
'chebi(Cofactor)',
'chebi-id',
'comment(COFACTOR)',
'comment(FUNCTION)',
'comment(KINETICS)',
'comment(PATHWAY)',
'comment(REDOX POTENTIAL)',
'comment(TEMPERATURE DEPENDENCE)',
'comment(PH DEPENDENCE)',
'feature(ACTIVE SITE)',
'feature(BINDING SITE)',
'feature(DNA BINDING)',
'feature(METAL BINDING)',
'feature(NP BIND)',
'feature(SITE)',
'annotation score',
'features',
'comment(CAUTION)',
'comment(MISCELLANEOUS)',
'keywords',
'existence',
'reviewed',
'comment(SUBUNIT)',
'interactor',
'comment(DEVELOPMENTAL STAGE)',
'comment(INDUCTION)',
'comment(TISSUE SPECIFICITY)',
'go',
'go(biological process)',
'go(molecular function)',
'go(cellular component)',
'go-id',
'comment(ALLERGEN)',
'comment(BIOTECHNOLOGY)',
'comment(DISRUPTION PHENOTYPE)',
'comment(DISEASE)',
'comment(PHARMACEUTICAL)',
'comment(TOXIC DOSE)',
'comment(SUBCELLULAR LOCATION)',
'feature(INTRAMEMBRANE)',
'feature(TOPOLOGICAL DOMAIN)',
'feature(TRANSMEMBRANE)',
'comment(PTM)',
'feature(CHAIN)',
'feature(CROSS LINK)',
'feature(DISULFIDE BOND)',
'feature(GLYCOSYLATION)',
'feature(INITIATOR METHIONINE)',
'feature(LIPIDATION)',
'feature(MODIFIED RESIDUE)',
'feature(PEPTIDE)',
'feature(PROPEPTIDE)',
'feature(SIGNAL)',
'feature(TRANSIT)',
'3d',
'feature(BETA STRAND)',
'feature(HELIX)',
'feature(TURN)',
'citationmapping',
'citation',
'created',
'last-modified',
'sequence-modified',
'version(entry)',
'comment(DOMAIN)',
'comment(SIMILARITY)',
'families',
'feature(COILED COIL)',
'feature(COMPOSITIONAL BIAS)',
'feature(DOMAIN EXTENT)',
'feature(MOTIF)',
'feature(REGION)',
'feature(REPEAT)',
'feature(ZINC FINGER)',
'lineage(all)',
'lineage(SUPERKINGDOM)',
'lineage(KINGDOM)',
'lineage(SUBKINGDOM)',
'lineage(SUPERPHYLUM)',
'lineage(PHYLUM)',
'lineage(SUBPHYLUM)',
'lineage(SUPERCLASS)',
'lineage(CLASS)',
'lineage(SUBCLASS)',
'lineage(INFRACLASS)',
'lineage(SUPERORDER)',
'lineage(ORDER)',
'lineage(SUBORDER)',
'lineage(INFRAORDER)',
'lineage(PARVORDER)',
'lineage(SUPERFAMILY)',
'lineage(FAMILY)',
'lineage(SUBFAMILY)',
'lineage(TRIBE)',
'lineage(SUBTRIBE)',
'lineage(GENUS)',
'lineage(SUBGENUS)',
'lineage(SPECIES GROUP)',
'lineage(SPECIES SUBGROUP)',
'lineage(SPECIES)',
'lineage(SUBSPECIES)',
'lineage(VARIETAS)',
'lineage(FORMA)',
'database(ABCD)',
'database(Allergome)',
'database(Antibodypedia)',
'database(ArachnoServer)',
'database(Araport)',
'database(Bgee)',
'database(BindingDB)',
'database(BioCyc)',
'database(BioGRID)',
'database(BioGRID-ORCS)',
'database(BioMuta)',
'database(BMRB)',
'database(BRENDA)',
'database(CarbonylDB)',
'database(CAZy)',
'database(CCDS)',
'database(CDD)',
'database(CGD)',
'database(ChEMBL)',
'database(ChiTaRS)',
'database(CLAE)',
'database(CollecTF)',
'database(ComplexPortal)',
'database(COMPLUYEAST-2DPAGE)',
'database(ConoServer)',
'database(CORUM)',
'database(CPTAC)',
'database(CPTC)',
'database(CTD)',
'database(dbSNP)',
'database(DDBJ)',
'database(DEPOD)',
'database(dictyBase)',
'database(DIP)',
'database(DisGeNET)',
'database(DisProt)',
'database(DMDM)',
'database(DNASU)',
'database(DOSAC-COBS-2DPAGE)',
'database(DrugBank)',
'database(DrugCentral)',
'database(EchoBASE)',
'database(eggNOG)',
'database(ELM)',
'database(EMBL)',
'database(Ensembl)',
'database(EnsemblBacteria)',
'database(EnsemblFungi)',
'database(EnsemblMetazoa)',
'database(EnsemblPlants)',
'database(EnsemblProtists)',
'database(ENZYME)',
'database(EPD)',
'database(ESTHER)',
'database(euHCVdb)',
'database(EvolutionaryTrace)',
'database(ExpressionAtlas)',
'database(FlyBase)',
'database(GenAtlas)',
'database(GenBank)',
'database(Gene3D)',
'database(GeneCards)',
'database(GeneDB)',
'database(GeneID)',
'database(GeneReviews)',
'database(GeneTree)',
'database(Genevisible)',
'database(GeneWiki)',
'database(GenomeRNAi)',
'database(GlyConnect)',
'database(GlyGen)',
'database(GO)',
'database(GPCRDB)',
'database(Gramene)',
'database(GuidetoPHARMACOLOGY)',
'database(HAMAP)',
'database(HGNC)',
'database(HOGENOM)',
'database(HPA)',
'database(HUGE)',
'database(IDEAL)',
'database(IMGT_GENE-DB)',
'database(InParanoid)',
'database(IntAct)',
'database(InterPro)',
'database(iPTMnet)',
'database(jPOST)',
'database(KEGG)',
'database(LegioList)',
'database(Leproma)',
'database(MaizeGDB)',
'database(MalaCards)',
'database(MassIVE)',
'database(MaxQB)',
'database(MEROPS)',
'database(MetOSite)',
'database(MGI)',
'database(Micado)',
'database(MIM)',
'database(MINT)',
'database(MobiDB)',
'database(ModBase)',
'database(MoonDB)',
'database(MoonProt)',
'database(neXtProt)',
'database(NIAGADS)',
'database(OGP)',
'database(OMA)',
'database(OpenTargets)',
'database(Orphanet)',
'database(OrthoDB)',
'database(PANTHER)',
'database(PathwayCommons)',
'database(PATRIC)',
'database(PaxDb)',
'database(PCDDB)',
'database(PDB)',
'database(PDBe-KB)',
'database(PDBj)',
'database(PDBsum)',
'database(PeptideAtlas)',
'database(PeroxiBase)',
'database(Pfam)',
'database(PharmGKB)',
'database(Pharos)',
'database(PHI-base)',
'database(PhosphoSitePlus)',
'database(PhylomeDB)',
'database(PIR)',
'database(PIRSF)',
'database(PlantReactome)',
'database(PomBase)',
'database(PRIDE)',
'database(PRINTS)',
'database(PRO)',
'database(ProMEX)',
'database(PROSITE)',
'database(Proteomes)',
'database(ProteomicsDB)',
'database(ProtoNet)',
'database(PseudoCAP)',
'database(RCSB-PDB)',
'database(Reactome)',
'database(REBASE)',
'database(RefSeq)',
'database(REPRODUCTION-2DPAGE)',
'database(RGD)',
'database(RNAct)',
'database(Rouge)',
'database(SABIO-RK)',
'database(SASBDB)',
'database(SFLD)',
'database(SGD)',
'database(SignaLink)',
'database(SIGNOR)',
'database(SMART)',
'database(SMR)',
'database(SOURCE)',
'database(STRING)',
'database(SUPFAM)',
'database(SWISS-2DPAGE)',
'database(SWISS-MODEL-Workspace)',
'database(SwissLipids)',
'database(SwissPalm)',
'database(TAIR)',
'database(TCDB)',
'database(TIGRFAMs)',
'database(TopDownProteomics)',
'database(TreeFam)',
'database(TubercuList)',
'database(UCD-2DPAGE)',
'database(UCSC)',
'database(UniLectin)',
'database(UniPathway)',
'database(VEuPathDB)',
'database(VGNC)',
'database(WBParaSite)',
'database(World-2DPAGE)',
'database(WormBase)',
'database(Xenbase)',
'database(ZFIN)']

# full_uniprot_cols = ['id',
# 'entry name',
# 'genes', 'sequence']
