name: asr_curation
channels:
  - defaults
dependencies:
  - bzip2
  - ca-certificates
  - certifi
  - libffi
  - ncurses
  - openssl
  - pip
  - python
  - readline
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - pip:
    - aiohttp
    - aiosignal
    - alabaster
    - anyio
    - appdirs
    - appnope
    - argon2-cffi
    - argon2-cffi-bindings
    - asttokens
    - async-timeout
    - attrs
    - babel
    - backcall
    - beautifulsoup4
    - biopython
    - bleach
    - brendapy
    - cached-property
    - cffi
    - chardet
    - charset-normalizer
    - colorama
    - commonmark
    - configargparse
    - connection-pool
    - cycler
    - datrie
    - debugpy
    - decorator
    - defusedxml
    - depinfo
    - docutils
    - dpath
    - entrypoints
    - executing
    - fastjsonschema
    - fastobo
    - fonttools
    - frozenlist
    - gitdb
    - gitpython
    - idna
    - imagesize
    - importlib-metadata
    - ipykernel
    - ipython
    - ipython-genutils
    - ipywidgets
    - isodate
    - jedi
    - jinja2
    - jsonschema
    - jupyter-book
    - jupyter-cache
    - jupyter-client
    - jupyter-core
    - jupyter-server
    - jupyter-server-mathjax
    - jupyter-sphinx
    - jupyterlab-pygments
    - jupyterlab-widgets
    - kiwisolver
    - latexcodec
    - linkify-it-py
    - lxml
    - markdown-it-py
    - markupsafe
    - matplotlib
    - matplotlib-inline
    - mdit-py-plugins
    - mistune
    - multidict
    - myst-nb
    - myst-parser
    - nbclient
    - nbconvert
    - nbdime
    - nbformat
    - nest-asyncio
    - networkx
    - notebook
    - numpy
    - packaging
    - pandas
    - pandocfilters
    - parso
    - pexpect
    - pickleshare
    - pillow
    - plac
    - platformdirs
    - prometheus-client
    - prompt-toolkit
    - pronto
    - psutil
    - ptyprocess
    - pulp
    - pure-eval
    - py
    - py3dmol
    - pybtex
    - pybtex-docutils
    - pycparser
    - pydantic
    - pydata-sphinx-theme
    - pygments
    - pymetadata
    - pyparsing
    - pyrsistent
    - python-dateutil
    - pytz
    - pyyaml
    - pyzmq
    - ratelimiter
    - requests
    - requests-file
    - requests-toolbelt
    - retry
    - rich
    - send2trash
    - six
    - smart-open
    - smmap
    - snakemake
    - sniffio
    - snowballstemmer
    - soupsieve
    - sphinx
    - sphinx-book-theme
    - sphinx-comments
    - sphinx-copybutton
    - sphinx-design
    - sphinx-external-toc
    - sphinx-jupyterbook-latex
    - sphinx-multitoc-numbering
    - sphinx-thebe
    - sphinx-togglebutton
    - sphinxcontrib-applehelp
    - sphinxcontrib-bibtex
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp
    - sphinxcontrib-jsmath
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml
    - sqlalchemy
    - stack-data
    - stopit
    - tabulate
    - terminado
    - tinycss2
    - toposort
    - tornado
    - traitlets
    - typing-extensions
    - uc-micro-py
    - ujson
    - urllib3
    - uuid
    - wcwidth
    - webencodings
    - websocket-client
    - widgetsnbextension
    - wrapt
    - xmltodict
    - yarl
    - yte
    - zeep
    - zipp
