name: tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version-file: '.python-version'
          cache: 'pip'

      - name: Install MAFFT
        run: sudo apt-get install mafft

      - name: Install FastTree
        run: sudo apt-get install fasttree

      - name: Download GRASP jar
        run: |
          curl -o bnkit.jar https://bodenlab.github.io/GRASP-suite/project/graspcmd/archive/bnkit_java_11.jar

      - name: Create grasp script
        run: |
          echo '#!/bin/sh' > grasp
          echo 'java -jar -Xmx16g "/usr/local/bin/bnkit.jar" "$@"' >> grasp

      - name: Make grasp script and bnkit.jar executable
        run: |
          chmod +x grasp
          chmod +x bnkit.jar

      - name: Move grasp script and bnkit.jar to /usr/local/bin
        run: |
          sudo mv grasp /usr/local/bin/
          sudo mv bnkit.jar /usr/local/bin/

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-coverage

      - name: Test with pytest
        run: |
          pytest --cov=/tmp/ --cov-append --cov-report=xml

      - name: Creating coverage folder
        run: |
          mkdir -p coverage

      - name: Generate coverage badge
        uses: tj-actions/coverage-badge-py@v1.8
        with:
          output: coverage/coverage.svg

      - name: Publish coverage report to coverage-badge branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: coverage-badge
          folder: coverage
